development:
  adapter: mysql2
  database: shop_dev
  host: localhost
  username: root
  password: qburst

production:
  adapter: mysql2
  database: shop_dev
  host: localhost
  username: root
  password: qburst

test:
  adapter: mysql2
  database: shop_dev
  host: localhost
  username: root
  password: qburst

integration1:
  adapter: mysql2
  database: shop_dev
  host: localhost
  username: root
  password: qburst

integration2:
  adapter: mysql2
  database: shop_dev
  host: localhost
  username: root
  password: qburst