development:
  adapter: mysql2
  database: euroso_development
  host: localhost
  username: root
  password: qburst

test:
  adapter: mysql2
  database: euroso_test
  host: localhost
  username: root
  password: qburst

production:
  adapter: mysql2
  database: euroso_production
  host: localhost
  username: root
  password: qburst

